name: Release

on:
  # If you push to main this will trigger a stable release
  push:
    branches:
      - master
      - main

  # Reusable workflow : Usually called by a `snapshot` workflow
  workflow_call:
    inputs:
      snapshot:
        description: "Is this a snapshot build?"
        required: false
        default: false
        type: boolean

  # Manually trigger the workflow
  workflow_dispatch:
    inputs:
      snapshot:
        description: "Is this a snapshot build?"
        required: false
        default: false
        type: boolean

env:
  PACKAGE_NAME: ${{ github.event.repository.name }}
  NODE_VERSION: 20
  SNAPSHOT: ${{ inputs.snapshot || false }}
  BUILD_ID: ${{ github.run_number }}

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup-env.outputs.version }}
      fileName: ${{ steps.setup-env.outputs.fileName }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i

      - name: Setup Build Environment
        id: setup-env
        run: |
            export PACKAGE_VERSION=`node -e "console.log( require('./package.json').version )"`
            export PACKAGE_FILE_NAME=`node -e "console.log( require('./package.json').name + '-' + require('./package.json').version + '.vsix')"`
            echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
            echo "PACKAGE_FILE_NAME=$PACKAGE_FILE_NAME" >> $GITHUB_ENV
            echo "fileName=${PACKAGE_FILE_NAME}" >> $GITHUB_OUTPUT
            echo "version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
            # Convert snippets to JSON
            ./buildSnippets.sh

      - name: Package Extension
        run: |
          npx vsce package

      - name: Upload package to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_FILE_NAME }}
          path: |
            ./${{ env.PACKAGE_FILE_NAME }}
          if-no-files-found: error

  # Publish to VS Marketplace
  publishMS:
    name: Publish to VS marketplace
    runs-on: ubuntu-latest
    needs: package
    # Only for master branch
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package.outputs.fileName }}

      - name: Publish to VS marketplace
        run: npx vsce publish --packagePath ./${{ needs.package.outputs.fileName }} -p ${{ secrets.VSCE_PAT }}

  # Publish to OpenVSX
  publishOVSX:
    name: Publish to OpenVSX
    runs-on: ubuntu-latest
    needs: package
    # Only for master branch
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package.outputs.fileName }}

      - name: Publish to OpenVSX
        run: npx ovsx publish ./${{ needs.package.outputs.fileName }} -p ${{ secrets.OVSX_PAT }}

  # Publish to GitHub Releases
  publishGH:
    name: Publish GitHub ${{ needs.package.outputs.version }}
    runs-on: ubuntu-latest
    needs: package
    # Only for master branch
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package.outputs.fileName }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Update changelog [unreleased] with latest version
        uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
        with:
          changelogPath: ./CHANGELOG.md
          tag: v${{ needs.package.outputs.version }}

      # Needed due to bug above
      - name: Fix Changelog
        run: |
            npm install -g markdownlint-cli
            markdownlint CHANGELOG.md --fix

      - name: Commit Changelog To Master
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: 'Finalized changelog for v${{ needs.package.outputs.version }}'
          add: CHANGELOG.md

      - name: Tag Version v${{ needs.package.outputs.version }}
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: "v${{ needs.package.outputs.version }}"
          force_push_tag: true
          message: "Latest Release v${{ needs.package.outputs.version }}"

      - name: Create Release v${{ needs.package.outputs.version }}
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.package.outputs.version }}
          release_name: v${{ needs.package.outputs.version }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload assets to a Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: |
            ${{ needs.package.outputs.fileName }}
          release-tag: v${{ needs.package.outputs.version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Upload CHANGELOG to the artifacts
      - name: Upload Changelog to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CHANGELOG
          path: CHANGELOG.md

  prepNextRelease:
    name: Bump New Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [ publishGH ]
    steps:
      # Checkout development
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: development

      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: CHANGELOG

      # NPM Minor Bump
      - name: Bump Version
        run: |
          npm version minor --no-git-tag-version

      # Commit it back
      - name: Commit Version Bump
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: 'Version bump'
          add: |
            package.json
            CHANGELOG.md

  # Publish artifact to S3
  publishS3:
    name: Publish to S3
    runs-on: ubuntu-latest
    needs: package
    if: success()
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.package.outputs.fileName }}
          path: upload

      - name: Display structure of downloaded files
        run: ls -R upload/

      - name: Upload Distributions to S3
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read
        env:
            AWS_S3_BUCKET: "downloads.ortussolutions.com"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
            SOURCE_DIR: "upload"
            DEST_DIR: "ortussolutions/vscode-boxlang/${{ needs.package.outputs.version }}"